GET http://localhost:3003/users
// Busca todos os usuários


###

GET http://localhost:3003/users/search?type=NORMAl
// Busca por nome do tipo


###


GET http://localhost:3003/users/search?type=NORMAl
// Busca por nome do tipo


###